post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkphdXphUGFzaSIsImlkIjoiNWZhZTM4MDVhYmJhYTIyOTUwMGMxOGFmIiwiaWF0IjoxNjA1NTYzMjg3fQ.fpTwQFiBnqG-aJz0yMnyw0D1qj8IR4eE9mk92lHQuGA

{
  "title": "Pasi ottaa iisiä",
  "url": "jauzamaa.com/chill"
}